### ISSUE TITLE
 john-chrosniak I need your help. To build it

### ISSUE THREAD

**Issue by KimJunHan** [linklab-uva/rosbag2nuscenes#12]
I just follow step by step you uplode it 

**git clone --recurse-submodules https://github.com/linklab-uva/rosbag2nuscenes.git && cd rosbag2nuscenes/
mkdir build/ && cd build/
cmake ..
make
./rosbag2nuscenes /path/to/bag/file /path/to/parameter/file**

when I am in  'cmake .. make' step. I got an error  can not  #include  rosbagstorage. 

develope environment: Ubuntu 20.04. ROS2 Foxy. 

I really need to train my deep learning model with nuScene data format to develop AutoDriving Car in real time

I really appriciate it for your help

I stay up all night watting your reply

Thanks.

**Comment by john-chrosniak** [comment]
If you're having trouble with the local build, I would recommend using the Docker image.

To build: 
`cd docker/`
`./build.sh`

To run:
`./run.sh /path/to/bag /path/to/config /path/to/dataset <num threads>`

**Comment by KimJunHan** [comment]
Thanks. I really appreciate it !!! it works!!!

**Comment by john-chrosniak** [comment]
Glad to hear it!
